# Build Options
#   change yes to no to disable

AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = no
SERIAL_DRIVER = vendor
CONSOLE_ENABLE = yes
